# Generated by Django 4.1.6 on 2023-02-13 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blacklist", "0002_player_created_at"),
    ]

    operations = [
        migrations.RenameModel(old_name="Player", new_name="PlayerReport",),
    ]
